---
title: "plotly"
author: "Muying Li"
date: "2025-10-29"
output: html_document
---


```{r message=FALSE}
library(tidyverse)
library(plotly)
library(p8105.datasets)
```

Load Instacart

Get a much smaller dataset for easier processing & deployment on internet
```{r}
data("nyc_airbnb")
nyc_airbnb = 
  nyc_airbnb |> 
  mutate(
    rating = review_scores_location/2
  ) |> 
  select(
    neighbourhood_group, neighbourhood, rating, price, room_type, lat, long
  ) |> 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <=500,
    price >=100
  )
```


Interactive scatterplot
```{r}
nyc_airbnb |>
  mutate(
    label = str_c("Price: $", price, "\nRating: ",rating)
  ) |> 
  plot_ly(
    x = ~lat, y= ~ long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers", alpha = 0.5
  )
```

Boxplot
```{r}
nyc_airbnb |> 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) |> 
  plot_ly(
    x=~neighbourhood,y=~price, color=~neighbourhood,
    type="box", colors = "viridis"
  )
```

Bar charts

how many airbnbs in each neighborhood
```{r}
nyc_airbnb |> 
  count(neighbourhood) |> 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) |> 
  plot_ly(
    x=~neighbourhood, y=~n, type = "bar"
  )
```

NOT recommended:
convert ggplot to ggplotly
```{r}
scatter_ggplot = 
  nyc_airbnb |>
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```


# Making dashboard


